site_name: RustyBT Documentation
site_description: Modern Python backtesting engine built on Zipline-Reloaded
site_author: RustyBT Development Team
site_url: https://jerryinyang.github.io/rustybt

repo_name: jerryinyang/rustybt
repo_url: https://github.com/jerryinyang/rustybt
edit_uri: edit/main/docs/

# Exclude files not meant for the documentation site
not_in_nav: |
  INDEX.md
  architecture.md
  prd.md
  experiments.md

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.ico

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            members_order: source

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jerryinyang/rustybt
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/rustybt/
  version:
    provider: mike

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Configuration: getting-started/configuration.md
  - User Guides:
      - Decimal Precision: guides/decimal-precision-configuration.md
      - Caching System: guides/caching-system.md
      - Creating Data Adapters: guides/creating-data-adapters.md
      - CSV Data Import: guides/csv-data-import.md
      - Testnet Setup: guides/testnet-setup-guide.md
  - API Reference:
      - Order Types: api/order-types.md
      - Caching API: api/caching-api.md
      - Bundle Metadata API: api/bundle-metadata-api.md
  - Architecture:
      - Overview: architecture/index.md
      - Introduction: architecture/introduction.md
      - Project Analysis: architecture/existing-project-analysis.md
      - Enhancement Strategy: architecture/enhancement-scope-and-integration-strategy.md
      - Tech Stack: architecture/tech-stack.md
      - Component Architecture: architecture/component-architecture.md
      - Data Models: architecture/data-models-and-schema-changes.md
      - External APIs: architecture/external-api-integration.md
      - Source Tree: architecture/source-tree.md
      - Infrastructure: architecture/infrastructure-and-deployment-integration.md
      - Coding Standards: architecture/coding-standards.md
      - Testing Strategy: architecture/testing-strategy.md
      - Security: architecture/security-integration.md
      - Data Catalog: architecture/data-catalog.md
      - Strategy Reusability: architecture/strategy-reusability-guarantee.md
      - Shadow Trading: architecture/shadow-trading-summary.md
      - Zipline Architecture: architecture/zipline-architecture-analysis.md
      - Epic 7 Rust Plan: architecture/epic-7-rust-optimization-plan.md
      - Epic 6 Docs: architecture/epic-6-critical-docs-reference.md
      - Epic 6 Gap Analysis: architecture/epic-6-gap-analysis-and-fixes.md
      - Change Log: architecture/change-log.md
      - Checklist Report: architecture/checklist-results-report.md
  - Product Requirements:
      - Goals & Context: prd/goals-and-background-context.md
      - Requirements: prd/requirements.md
      - MVP Scope: prd/mvp-scope.md
      - Out of Scope: prd/out-of-scope.md
      - Epic List: prd/epic-list.md
      - Technical Assumptions: prd/technical-assumptions.md
      - Epic 1 - Foundation: prd/epic-1-foundation-core-infrastructure.md
      - Epic 2 - Decimal: prd/epic-2-financial-integrity-decimal-arithmetic.md
      - Epic 3 - Data Architecture: prd/epic-3-modern-data-architecture-mvp-data-sources.md
      - Epic 3 - Sequence: prd/epic-3-implementation-sequence.md
      - Epic 4 - Transaction Costs: prd/epic-4-enhanced-transaction-costs-multi-strategy-portfolio.md
      - Epic 5 - Optimization: prd/epic-5-strategy-optimization-robustness-testing.md
      - Epic 6 - Live Trading: prd/epic-6-live-trading-engine-broker-integrations.md
      - Epic 8 - Analytics: prd/epic-8-analytics-production-readiness.md
      - Epic 9 - REST API: prd/epic-9-restful-api-websocket-interface-lowest-priority.md
      - Checklist Report: prd/checklist-results-report.md
  - Completed Stories:
      - Story 1.1 - Fork & Setup: stories/completed/1.1.fork-repository-and-establish-development-environment.md
      - Story 1.2 - CI/CD: stories/completed/1.2.configure-cicd-pipeline.md
      - Story 1.3 - Architecture Map: stories/completed/1.3.map-existing-architecture-and-identify-extension-points.md
      - Story 1.4 - Data Pipeline: stories/completed/1.4.extend-data-pipeline-with-metadata-tracking.md
      - Story 1.5 - Order Types: stories/completed/1.5.add-advanced-order-types.md
      - Story 1.6 - Metrics: stories/completed/1.6.implement-additional-performance-metrics.md
      - Story 1.7 - Event System: stories/completed/1.7.enhance-backtest-engine-event-system.md
      - Story 2.1 - Decimal Config: stories/completed/2.1.design-decimal-precision-configuration-system.md
      - Story 2.2 - Decimal Calc: stories/completed/2.2.replace-float-with-decimal-in-core-calculation-engine.md
      - Story 2.3 - Decimal Orders: stories/completed/2.3.replace-float-with-decimal-in-order-execution-system.md
      - Story 2.5 - Decimal Pipeline: stories/completed/2.5.replace-float-with-decimal-in-data-pipelines.md
      - Story 2.5.5 - Complete Pipeline: stories/completed/2.5.5.complete-decimal-data-pipeline-integration.md
      - Story 2.6 - Property Testing: stories/completed/2.6.implement-property-based-testing-for-financial-calculations.md
      - Story 2.7 - Performance: stories/completed/2.7.document-performance-baselines-for-rust-optimization.md
      - Story 3.1 - Data Catalog: stories/completed/3.1.design-unified-data-catalog-architecture.md
      - Story 3.2 - Parquet: stories/completed/3.2.implement-parquet-storage-layer-with-metadata-catalog.md
      - Story 3.3 - Caching: stories/completed/3.3.implement-intelligent-local-caching-system.md
      - Story 3.4 - Base Adapter: stories/completed/3.4.implement-base-data-adapter-framework.md
      - Story 3.5 - CCXT Adapter: stories/completed/3.5.implement-ccxt-data-adapter.md
      - Story 3.6 - yFinance: stories/completed/3.6.implement-yfinance-data-adapter.md
      - Story 3.7 - CSV Adapter: stories/completed/3.7.implement-csv-data-adapter-with-schema-mapping.md
      - Story 3.8 - Aggregation: stories/completed/3.8.implement-multi-resolution-aggregation-with-ohlcv-validation.md
      - Story 4.1 - Latency: stories/completed/4.1.implement-latency-simulation.md
      - Story 4.2 - Partial Fills: stories/completed/4.2.implement-partial-fill-model.md
      - Story 4.3 - Slippage: stories/completed/4.3.implement-multiple-slippage-models.md
      - Story 4.4 - Commission: stories/completed/4.4.implement-tiered-commission-models.md
      - Story 4.5 - Borrow Costs: stories/completed/4.5.implement-borrow-cost-model-for-short-selling.md
      - Story 4.6 - Overnight: stories/completed/4.6.implement-overnight-financing-for-leveraged-positions.md
      - Story 4.7 - Allocator: stories/completed/4.7.implement-portfolio-allocator-for-multi-strategy-management.md
      - Story 4.8 - Capital Allocation: stories/completed/4.8.implement-capital-allocation-algorithms.md
      - Story 4.9 - Risk Management: stories/completed/4.9.implement-cross-strategy-risk-management.md
      - Story 4.10 - Order Aggregation: stories/completed/4.10.implement-order-aggregation-across-strategies.md
      - Story 5.1 - Optimization Framework: stories/completed/5.1.design-optimization-framework-architecture.md
      - Story 5.2 - Grid Search: stories/completed/5.2.implement-grid-search-algorithm.md
      - Story 5.3 - Random Search: stories/completed/5.3.implement-random-search-algorithm.md
      - Story 5.4 - Bayesian: stories/completed/5.4.implement-bayesian-optimization-algorithm.md
      - Story 5.5 - Genetic: stories/completed/5.5.implement-genetic-algorithm-optimization.md
      - Story 5.6 - Parallel: stories/completed/5.6.implement-parallel-processing-framework.md
      - Story 5.7 - Walk Forward: stories/completed/5.7.implement-walk-forward-optimization-framework.md
      - Story 5.8 - Sensitivity: stories/completed/5.8.implement-parameter-sensitivity-stability-analysis.md
      - Story 5.9 - Monte Carlo Permutation: stories/completed/5.9.implement-monte-carlo-data-permutation.md
      - Story 5.10 - Monte Carlo Noise: stories/completed/5.10.implement-monte-carlo-noise-infusion.md
  - Quality Assurance:
      - Test Results: qa/TEST-EXECUTION-RESULTS.md
      - Enhancements Summary: qa/ENHANCEMENTS-SUMMARY.md
      - QA Improvements: qa/QA-IMPROVEMENTS-SUMMARY.md
  - About:
      - License: about/license.md
      - Contributing: about/contributing.md
      - Changelog: about/changelog.md
