site_name: RustyBT Documentation
site_description: Modern Python backtesting engine built on Zipline-Reloaded
site_author: RustyBT Development Team
site_url: https://jerryinyang.github.io/rustybt

repo_name: jerryinyang/rustybt
repo_url: https://github.com/jerryinyang/rustybt
edit_uri: edit/main/docs/

# Exclude files and directories not meant for the documentation site
not_in_nav: |
  architecture.md
  prd.md
  experiments.md

# Exclude internal documentation directories from search and build
exclude: |
  architecture/
  stories/
  qa/
  reviews/
  development/
  validation/
  pr/
  prd/
  performance/
  testing/
  **/AUDIT_REPORT*.md
  **/CORRECTIONS_SUMMARY.md
  **/CODE_VALIDATION.md
  **/CODE_EXAMPLES_VALIDATION.md
  EPIC_10_*.md
  DOCUMENTATION-SETUP.md
  security-audit.md
  **/architecture.md
  **/prd.md


theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.ico

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
            members_order: source

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jerryinyang/rustybt
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/rustybt/
  version:
    provider: mike

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Configuration: getting-started/configuration.md
  - User Guides:
      - Decimal Precision: guides/decimal-precision-configuration.md
      - Caching System: guides/caching-system.md
      - Creating Data Adapters: guides/creating-data-adapters.md
      - CSV Data Import: guides/csv-data-import.md
      - Testnet Setup: guides/testnet-setup-guide.md
  - Examples & Tutorials:
      - Overview: examples/README.md
  - API Reference:
      - Data Management:
          - Overview: api/data-management/README.md
          - Adapters:
              - Overview: api/data-management/adapters/overview.md
              - CCXT: api/data-management/adapters/ccxt.md
              - YFinance: api/data-management/adapters/yfinance.md
              - CSV: api/data-management/adapters/csv.md
              - Polygon: api/data-management/adapters/polygon.md
              - Alpaca: api/data-management/adapters/alpaca.md
              - AlphaVantage: api/data-management/adapters/alphavantage.md
          - Catalog:
              - Bundles: api/data-management/catalog/bundles.md
              - Migration: api/data-management/catalog/migration.md
          - Readers:
              - Data Portal: api/data-management/readers/data-portal.md
              - Bar Readers: api/data-management/readers/bar-readers.md
              - History Loader: api/data-management/readers/history-loader.md
              - Continuous Futures: api/data-management/readers/continuous-futures.md
          - FX System:
              - Overview: api/data-management/fx/overview.md
              - Providers: api/data-management/fx/providers.md
              - Storage: api/data-management/fx/storage.md
              - Converters: api/data-management/fx/converters.md
          - Pipeline:
              - Overview: api/data-management/pipeline/overview.md
              - Factors: api/data-management/pipeline/factors.md
              - Filters: api/data-management/pipeline/filters.md
              - Loaders: api/data-management/pipeline/loaders.md
              - Expressions: api/data-management/pipeline/expressions.md
          - Performance:
              - Caching: api/data-management/performance/caching.md
              - Optimization: api/data-management/performance/optimization.md
              - Troubleshooting: api/data-management/performance/troubleshooting.md
      - Order Management:
          - Overview: api/order-management/README.md
          - Order Types: api/order-management/order-types.md
          - Execution:
              - Blotter: api/order-management/execution/blotter.md
          - Transaction Costs:
              - Slippage: api/order-management/transaction-costs/slippage.md
              - Commissions: api/order-management/transaction-costs/commissions.md
          - Workflows:
              - Order Lifecycle: api/order-management/workflows/order-lifecycle.md
              - Examples: api/order-management/workflows/examples.md
      - Portfolio Management:
          - Overview: api/portfolio-management/README.md
          - Multi-Strategy:
              - Allocators: api/portfolio-management/multi-strategy/allocators.md
          - Risk:
              - Position Limits: api/portfolio-management/risk/position-limits.md
          - Performance:
              - Metrics: api/portfolio-management/performance/metrics.md
      - Optimization:
          - Overview: api/optimization/README.md
          - Framework:
              - Architecture: api/optimization/framework/architecture.md
              - Parameter Spaces: api/optimization/framework/parameter-spaces.md
              - Objective Functions: api/optimization/framework/objective-functions.md
          - Algorithms:
              - Grid Search: api/optimization/algorithms/grid-search.md
              - Random Search: api/optimization/algorithms/random-search.md
              - Bayesian: api/optimization/algorithms/bayesian.md
              - Genetic: api/optimization/algorithms/genetic.md
          - Walk-Forward:
              - Framework: api/optimization/walk-forward/framework.md
              - Windows: api/optimization/walk-forward/windows.md
              - Validation: api/optimization/walk-forward/validation.md
          - Monte Carlo:
              - Stability Testing: api/optimization/monte-carlo/stability-testing.md
          - Parallel:
              - Multiprocessing: api/optimization/parallel/multiprocessing.md
          - Best Practices:
              - Overfitting Prevention: api/optimization/best-practices/overfitting-prevention.md
      - Analytics:
          - Overview: api/analytics/README.md
          - Risk:
              - Metrics: api/analytics/risk/metrics.md
              - VaR & CVaR: api/analytics/risk/var-cvar.md
              - Drawdown: api/analytics/risk/drawdown.md
      - Live Trading:
          - Overview: api/live-trading/README.md
      - Testing:
          - Overview: api/testing/README.md
      - API Overview Guides:
          - Datasource API: api/datasource-api.md
          - Optimization API: api/optimization-api.md
          - Analytics API: api/analytics-api.md
  - About:
      - License: about/license.md
      - Contributing: about/contributing.md
      - Changelog: about/changelog.md
