"""Regression test generation for verified bug fixes.

This module provides functionality to auto-generate pytest tests for
bugs that have been fixed and verified. Generated tests ensure bugs
don't reappear in future development.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from rustybt.validation.models import Finding

# Default regression test directory relative to project root
REGRESSION_DIR = Path("tests/validation/regression")

# Mapping from layer name to pytest marker
LAYER_TO_MARKER = {
    "data": "layer_1_data",
    "signals": "layer_2_signals",
    "orders": "layer_3_orders",
    "broker": "layer_4_broker",
    "portfolio": "layer_5_portfolio",
}


def generate_regression_test(finding: Finding, project_root: Path | None = None) -> Path:
    """Generate a regression test for a verified bug fix.

    Creates a pytest test file that verifies the specific discrepancy
    from the finding is no longer present.

    Args:
        finding: The verified finding to generate a test for
        project_root: Root directory of the project (default: cwd)

    Returns:
        Path to the generated test file
    """
    if project_root is None:
        project_root = Path.cwd()

    # Ensure directory exists
    regression_dir = project_root / REGRESSION_DIR
    regression_dir.mkdir(parents=True, exist_ok=True)

    # Create __init__.py if not exists
    init_file = regression_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text(
            "# Regression tests for fixed bugs\n"
            "#\n"
            "# Auto-generated by rustybt-validate verify\n"
        )

    # Generate test file path from finding ID
    test_name = _sanitize_test_name(finding.id)
    test_file = regression_dir / f"test_{test_name}.py"

    # Generate test content
    content = generate_test_content(finding)

    # Write test file
    test_file.write_text(content)

    return test_file


def _sanitize_test_name(finding_id: str) -> str:
    """Convert finding ID to valid Python identifier for test name.

    Args:
        finding_id: Finding ID (e.g., "FIND-001", "layer_3_finding_001")

    Returns:
        Sanitized name (e.g., "find_001", "layer_3_finding_001")
    """
    # Convert to lowercase and replace hyphens with underscores
    name = finding_id.lower().replace("-", "_")
    # Remove any invalid characters
    name = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    # Ensure doesn't start with number
    if name and name[0].isdigit():
        name = "f_" + name
    return name


def generate_test_content(finding: Finding) -> str:
    """Generate Python test code for a verified finding.

    Args:
        finding: The finding to generate test content for

    Returns:
        Python source code for the test file
    """
    test_name = _sanitize_test_name(finding.id)
    layer_marker = LAYER_TO_MARKER.get(finding.layer, "regression")

    # Format resolved date
    resolved_date = "N/A"
    if finding.resolved_at:
        resolved_date = finding.resolved_at.strftime("%Y-%m-%d")

    # Format affected components
    affected = ", ".join(finding.affected_components) if finding.affected_components else "N/A"

    # Extract event type from description if not directly available
    event_filter = _extract_event_type(finding)

    # Determine strategy fixture (default to generic)
    strategy_fixture = "regression_test_logs"

    content = f'''"""
Regression test for {finding.id}

Original finding:
- Layer: {finding.layer}
- Description: {finding.description}
- rustybt: {finding.rustybt_value}, Backtrader: {finding.backtrader_value}

Fixed: {resolved_date}
Rationale: {finding.rationale or "N/A"}
Affected: {affected}
"""
import pytest
from rustybt.validation.comparators import (
    Layer1DataComparator,
    Layer2SignalComparator,
    Layer3OrdersComparator,
    Layer4BrokerComparator,
    Layer5PortfolioComparator,
)
from rustybt.validation.tolerance import ToleranceConfig


def _get_comparator(layer: str):
    """Get comparator for layer."""
    comparators = {{
        "data": Layer1DataComparator,
        "signals": Layer2SignalComparator,
        "orders": Layer3OrdersComparator,
        "broker": Layer4BrokerComparator,
        "portfolio": Layer5PortfolioComparator,
    }}
    return comparators[layer]()


@pytest.mark.regression
@pytest.mark.{layer_marker}
def test_{test_name}({strategy_fixture}):
    """
    Verify fix for {finding.id} has not regressed.

    Original issue: {finding.description}
    """
    comparator = _get_comparator("{finding.layer}")

    result = comparator.compare(
        {strategy_fixture}["rustybt"],
        {strategy_fixture}["backtrader"],
    )

    # Check for the specific discrepancy that was fixed
    matching_discrepancies = [
        d for d in result.discrepancies
        if "{event_filter}".lower() in d.description.lower()
        or "{event_filter}".lower() in (d.event or "").lower()
    ]

    assert len(matching_discrepancies) == 0, (
        f"Regression detected: {finding.id} may have reappeared. "
        f"Found {{len(matching_discrepancies)}} matching discrepancies. "
        f"Original issue: {finding.description}"
    )
'''
    return content


def _extract_event_type(finding: Finding) -> str:
    """Extract event type identifier from finding.

    Attempts to extract a meaningful event type from the finding's
    description or other fields for filtering discrepancies.

    Args:
        finding: Finding to extract event type from

    Returns:
        Event type string for filtering
    """
    # If finding has event field (from some implementations), use it
    if hasattr(finding, "event") and finding.event:
        return finding.event

    # Try to extract from description
    description = finding.description.lower()

    # Common patterns
    if "mismatch" in description:
        # Extract what's mismatching (e.g., "price mismatch" -> "price_mismatch")
        parts = description.split("mismatch")
        if parts:
            prefix = parts[0].strip().split()[-1] if parts[0].strip() else ""
            if prefix:
                return f"{prefix}_mismatch"
        return "mismatch"

    if ":" in finding.description:
        # Pattern like "layer/event_type: description"
        parts = finding.description.split(":")
        event_part = parts[0].strip()
        if "/" in event_part:
            return event_part.split("/")[-1]
        return event_part

    # Fall back to using first few words
    words = finding.description.split()[:3]
    return "_".join(words).lower()


def generate_cli_command() -> str:
    """Generate CLI command hint for running regression tests.

    Returns:
        Command string for running regression tests
    """
    return "pytest tests/validation/regression/ -v --tb=short"
